### ISSUE TITLE
YamlFileLoader->load() issue

### ISSUE THREAD

**Issue by Sc3n3** [lennerd/vipx-bot-detect#22]
35.line should change to
$content = Yaml::parse(file_get_contents($file));

Because Yaml::parse method is changed. It needs string.

**Comment by swen100** [comment]
After some examination: that is correct. 
The Symphony docs say:
"Passing a file as an input is a deprecated feature and will be removed in 3.0".
In the previous version it is also possible to give the contents of a file directly. So it gets no harm to use "file_get_contents()" directly.

**Comment by lennerd** [comment]
@Sc3n3 thanks for pointing this out and @swen100 thanks for creating a PR to fix this.
